[package]
name = "piston-test"
version = "0.1.0"
authors = ["Andy Barron <AndrewLBarron@gmail.com>"]

[dependencies]
piston = "*"
piston2d-graphics = "*"
pistoncore-glutin_window = "*"
piston2d-opengl_graphics = "*"